# Generated by Django 2.2.5 on 2019-11-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfaces',
            old_name='project',
            new_name='project_id',
        ),
    ]
