# Generated by Django 2.2.5 on 2019-11-07 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_auto_20191107_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='project_id',
            field=models.ForeignKey(db_column='project_id', help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='projects.Projects'),
        ),
    ]
