# Generated by Django 2.2.5 on 2019-11-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0003_auto_20191107_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfaces',
            old_name='project_id',
            new_name='project',
        ),
    ]
