# Generated by Django 2.2.5 on 2019-11-09 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0004_auto_20191109_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='project',
            field=models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='projects.Projects'),
        ),
    ]
