# Generated by Django 2.2.5 on 2019-10-15 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='接口名称', max_length=200, verbose_name='接口名称')),
                ('url', models.CharField(help_text='接口地址', max_length=100, unique=True, verbose_name='接口地址')),
                ('data', models.CharField(blank=True, help_text='接口参数', max_length=100, null=True, verbose_name='参数')),
                ('projects', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='projects.Projects', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '接口模块',
                'verbose_name_plural': '接口模块',
            },
        ),
    ]
