# Generated by Django 2.2.5 on 2019-10-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interface',
            options={'ordering': ['name'], 'verbose_name': '接口模块', 'verbose_name_plural': '接口模块'},
        ),
        migrations.AlterField(
            model_name='interface',
            name='projects',
            field=models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='_interfaces', to='projects.Projects', verbose_name='所属项目'),
        ),
    ]
