# Generated by Django 2.2.5 on 2019-11-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, default='17706120671', help_text='手机号码', max_length=11, null=True, verbose_name='手机号码'),
        ),
    ]
